### ISSUE TITLE
PduHeader has invalid length and status attributes

### ISSUE THREAD

**Issue by delaneyj** [open-dis/DISDescription#3]
Per the 1278.1-2012 spec for PduHeader

> Length. This field shall specify the length of the PDU, including the PDU Header, in octets and shall be represented by a 16-bit unsigned integer....
> PDU Status...This record shall be defined as an 8-bit record....

The spec goes into further details on the fields.  However the DIS7.xml and all generated code has incorrect sizing of these fields.  Given this is the basis for all PDUs how do any of the generated implementations correctly generate or read any messages streams correctly?

**Comment by leif81** [comment]
Thank you for the report @delaneyj 

To be honest, I only use the DIS6 implementation (the Java and C++ ones), so I don't have experience using the DIS7 implementation to confirm your observation.

If you have some sample DIS7 PDU's what you could do is submit a pull request with a unit test in the open-dis-java project to confirm it fails to parse them.

**Comment by kurtsansom** [comment]
This appears to be resolved?
PduHeader is not used, Pdu inherits PduSuplerClass

**Comment by delaneyj** [comment]
Not that I'm aware of, I instead built a Go lib by head directly from the spec.
